// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjYRhykqQU8bfkUjtL1f6v_6f5x7B226o',
    appId: '1:1097454828280:web:73c0975ac212ffc6abd90d',
    messagingSenderId: '1097454828280',
    projectId: 'project5-8fe18',
    authDomain: 'project5-8fe18.firebaseapp.com',
    storageBucket: 'project5-8fe18.appspot.com',
    measurementId: 'G-NJ5HMHF0HY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQfWK_8y8iIuwxKSXact8JxE2lKhi1a70',
    appId: '1:1097454828280:android:edf5567575d0a502abd90d',
    messagingSenderId: '1097454828280',
    projectId: 'project5-8fe18',
    storageBucket: 'project5-8fe18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGjQAchUHkLE-kE6ygKIziY4EtkJOSQvM',
    appId: '1:1097454828280:ios:5f435f3aa0a4f0e8abd90d',
    messagingSenderId: '1097454828280',
    projectId: 'project5-8fe18',
    storageBucket: 'project5-8fe18.appspot.com',
    iosClientId: '1097454828280-gagbl3ia2bgej0fap5aiu835tuoco0q8.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGjQAchUHkLE-kE6ygKIziY4EtkJOSQvM',
    appId: '1:1097454828280:ios:5f435f3aa0a4f0e8abd90d',
    messagingSenderId: '1097454828280',
    projectId: 'project5-8fe18',
    storageBucket: 'project5-8fe18.appspot.com',
    iosClientId: '1097454828280-gagbl3ia2bgej0fap5aiu835tuoco0q8.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled4',
  );
}
